name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e .[dev]
      - name: Test evaluation notebook
        run: |
          pytest --nbmake notebooks/evaluation.ipynb --nbmake-kernel=python3
